# Pytest
[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "--strict-markers --disable-pytest-warnings"
markers = [
    "image: tests that involves images in APIs",
    "video: tests that involves videos in APIs",
]