{
 "title": "Visdrone",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Health check",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"drone\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Status count",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(visdrone_model_http_requests_total{job='drone'})by(status) "
    }
   ]
  },
  {
   "title": "Requests count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(visdrone_model_http_requests_total)"
    }
   ]
  },
  {
   "title": "Image response time",
   "type": "bargauge",
   "description": "Response Time for succeeded Images API",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "visdrone_model_http_request_duration_seconds_bucket{handler=\"/predictions/images\", status=\"2xx\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Images Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(visdrone_model_http_requests_total{handler=\"/predictions/images\"})"
    }
   ]
  },
  {
   "title": "Video response time",
   "type": "bargauge",
   "description": "Response Time for succeeded videos API",
   "gridPos": { "h": 9, "w": 9, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "visdrone_model_http_request_duration_seconds_bucket{handler=\"/predictions/videos\", status=\"2xx\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Videos Count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(visdrone_model_http_requests_total{handler=\"/predictions/videos\"})"
    }
   ]
  },
  {
   "title": "Count Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "visdrone_model_people_count_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Query Counting",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "visdrone_model_query_parameter_count_total"
    }
   ]
  }
 ]
}