{
 "title": "Visdrone",
 "time": { "from": "2021-12-13T17:41:24.611Z", "to": "2021-12-13T18:41:24.611Z" },
 "panels": [
  {
   "title": "Image response time",
   "type": "bargauge",
   "description": "Response Time for succeeded Images API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "visdrone_model_http_request_duration_seconds_bucket{handler=\"/predictions/images\", status=\"2xx\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Video response time",
   "type": "bargauge",
   "description": "Response Time for succeeded videos API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "visdrone_model_http_request_duration_seconds_bucket{handler=\"/predictions/videos\", status=\"2xx\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Count Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 1, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "visdrone_model_people_count_bucket",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}